---
- name: Restart Dock
  shell: |
    killall Dock

- name: Restart Finder
  shell: |
    killall Finder

- name: Setup Karabiner
  shell: |
    ./karabiner.sh
  args:
    chdir: roles/mac/files/bin
